name: "Clean Actions"

on:
  push:
  schedule:
    - cron: "0 0 * * 1"

permissions:
  actions: write

jobs:
  run:
    name: Cleanup
    uses: theantiscamgroup/workflows/.github/workflows/clean_actions.yml@main