name: "Clean Actions"

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  run:
    name: Cleanup
    uses: socksthewolf/workflows/.github/workflows/clean.yml@main
    secrets:
      CLEAN_TOKEN: ${{ secrets.GITHUB_TOKEN }}