name: Deploy Bot
on:
  push:
    branches:
      - prod

  workflow_dispatch:
    inputs:
        restart_bot:
            description: 'Restart Bot Instances'
            required: true
            type: boolean

# Prevent multiple instances of this action from running at once
concurrency:
  group: "deploy"
  cancel-in-progress: false

permissions:
  deployments: write
  contents: read

jobs:
  check_prod:
    runs-on: ubuntu-latest
    steps:
      # Error out if not prod
      - name: Verify Branch is Prod
        if: github.ref != 'refs/heads/prod'
        run: exit 1

  deploy:
    uses: theantiscamgroup/workflows/.github/workflows/deploy_bot.yml@main
    secrets: inherit
    with:
      ref: ${{ github.ref }}
      path: "~/project/AntiScamBot"
      force_restart: ${{ inputs.restart_bot }}
